version: '3.8'

services:
  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_DATABASE: linkedin
      MYSQL_ROOT_PASSWORD: B@a#cc$o-8945
    ports:
      - '3306:3306'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'